sudo: required
language: bash
env:
  global:
    - IMAGE_NAME=gableroux/unity3d:latest
    - BUILD_NAME=planet-ball
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_ce143bb546cb_key -iv
    $encrypted_ce143bb546cb_iv -in Unity_v2019.x.ulf.enc -out ./Unity_v2019.x.ulf -d
  - export UNITY_LICENSE_CONTENT=`cat Unity_v2019.x.ulf`
  - rm Unity_v2019.x.ulf
  - docker pull $IMAGE_NAME
jobs:
  include:
    - stage: build
      env: BUILD_TARGET=StandaloneWindows64
      script:
        - "chmod +x ./ci/* && ./ci/docker_build.sh"
        - "sudo chmod -R 777 ./Builds/"
        - "cd ./Builds/"
        - "zip -r StandaloneWindows64.zip ./StandaloneWindows64/"
      deploy:
        provider: releases
        api_key: $GITHUB_API_KEY
        file: StandaloneWindows64.zip
        skip_cleanup: true
        on:
          tags: true